Task 2_4 has been done
Godis715/Homework pull request #4
Opened 2018-03-05 20:19 UTC by Godis715

2018-03-08 13:58 UTC, yurii-litvinov requested changes

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/Calculator.cs
> +		IStack stack;
По стайлгайду положено явно писать, что поле private

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/Calculator.cs
> +		public int GetTop()
Тут скорее не GetTop, а Result или что-то такое. Калькулятор не должен давать знать пользователям, что внутри у него стек, принцип абстракции же

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/Calculator.cs
> +			stack.Push(number);
Правильнее было сделать метод Top стеку

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/Calculator.cs
> +		private Tuple<int, int> GetTwoNumbers()
Тут лучше кортежи использовать --- `private (int, int) GetTwoNumbers()`. Tuple хорошо, но выделяется на куче, так что неоправданно грузит сборщик мусора

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/Calculator.cs
> +			}
В современном C# можно `int rightNumber = !stack.IsEmpty ? stack.Pop() : throw new IndexOutOfRangeException();`

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/Calculator.cs
> +			}
И опять-таки, IndexOutOfRangeException тут не очень подходит, потому что какой индекс? :)

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/CalculatorTests/CalculatorTests.csproj
> +    <Compile Include="Class1.cs" />
Что-то этот файл не выложен. И заывается как-то странно

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/CalculatorTests/Tests.cs
> +﻿using System;
А этого файла нет в проекте :)

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/CalculatorTests/Tests.cs
> +		}
Очень длинный тест, который надо разбить на 4

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/StackByArray.cs
> +		}
Это можно в одну строчку записать

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/StackByArray.cs
> +		private bool isEmpty;
Кажется, isEmpty == (currentIndex == -1), так что его можно не хранить

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/StackByArray.cs
> +		public int Pop()
Надо пустую строчку между методами

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/StackByArray.cs
> +				throw new IndexOutOfRangeException("Stack overflow.");
IndexOutOfRangeException тут тоже не очень

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/StackByNodes.cs
> +		private bool isEmpty;
Тоже хранить незачем, это можно быстро проверить по head

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/StackByNodes.cs
> +		}
Проще `public bool IsEmpty => head ==  null;`

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/StackByNodes.cs
> +			head = null;
Она и так null

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/StackByNodes.cs
> +			newNode.Prev = head;
Лучше тут использовать инициализатор, или добавить в конструктор ещё один параметр

2018-03-08 13:58 UTC, yurii-litvinov commented on HwProj_Task_2_4/StackByNodes.cs
> +				throw new IndexOutOfRangeException();
Тоже не оч

2018-03-10 10:38 UTC, Godis715 commented on HwProj_Task_2_4/Calculator.cs
> +		IStack stack;
Поправил

2018-03-10 10:40 UTC, Godis715 commented on HwProj_Task_2_4/Calculator.cs
> +		public int GetTop()
Исправил

2018-03-10 10:42 UTC, Godis715 commented on HwProj_Task_2_4/Calculator.cs
> +			stack.Push(number);
Ведь Top можно реализовать Pop-ом и Push-ом
Думаю, стеку не обязательно давать значение вершины

2018-03-10 10:42 UTC, Godis715 commented on HwProj_Task_2_4/Calculator.cs
> +		private Tuple<int, int> GetTwoNumbers()
Поправил
Но пришлось дополнительно устанавливать кортежи
Ничего, что у кого-то может не быть этого расширения?

2018-03-10 11:05 UTC, Godis715 commented on HwProj_Task_2_4/Calculator.cs
> +			}
Переписал более коротким способом

2018-04-01 15:21 UTC, yurii-litvinov requested changes
Выложите проект, я бы посмотрел, что не так с тестами.

2018-04-01 15:21 UTC, yurii-litvinov commented on HwProj_Task_2_4/Calculator.cs
> +			stack.Push(number);
Можно, но очень неэффективно --- если стек не на массиве, это лишнее выделение памяти.

2018-04-01 15:21 UTC, yurii-litvinov commented on HwProj_Task_2_4/Calculator.cs
> +		private Tuple<int, int> GetTwoNumbers()
- с .NET Framework 4.7 кортежи являются частью стандартной библиотеки
- "расширения" качаются прямо в процессе сборки из репозиториев с помощью пакетного менеджера NuGet. теоретически у кого-то может не быть интернет-соединения, но в таком случае программировать на .NET будет и без того плохо

2019-09-08 18:42 UTC, merged